### ISSUE TITLE
Token doesn’t work for repos not owned by me, but I yo which I have access.

### ISSUE THREAD

**Issue by davidcsi** [chouglesaud/repositree#2]
**Describe the bug**
Using a token I can see MY private repos, but not othe private repos to which I have access.

**To Reproduce**
Create a token and try to access repos not owned by you

Continuing our conversation, I'd for for a simple GitHub auth integration.

Cheers!

**Comment by chouglesaud** [comment]
> Using a token I can see MY private repos, but not other private repos to which I have access.

it's because the **personal** access token has a limitation.

> Continuing our conversation, I'd for a simple GitHub auth integration.

I also think so, I am working on it.

thanks, @davidcsi. you can see this feature in the next update that gonna released soon.

**Comment by chouglesaud** [comment]
Repositree v1.1.7
GitHub Auth Added to Get access token
Update the extension :+1: 
@davidcsi
