### ISSUE TITLE
Repositree extension doesn't work when address bar has a question mark

### ISSUE THREAD

**Issue by liyuhang1997** [chouglesaud/repositree#5]
**Describe the bug**
When the address bar has a question mark, this extension does not work

**To Reproduce**
1. Open https://github.com/chouglesaud/repositree, it works fine.
2. Open https://github.com/chouglesaud/repositree?ref=producthunt, it doesn't work!

- Repositree Version: 1.5.0

**Comment by chouglesaud** [comment]
@liyuhang1997 thanks :+1:   

bug fixed in v1.5.1 :package: 
update the extension
