### ISSUE TITLE
Repositree extension doesn't work when address bar has a backslash

### ISSUE THREAD

**Issue by liyuhang1997** [chouglesaud/repositree#8]
**Describe the bug**
When the address bar has a backslash, this extension does not work.
Similar to #5.

**To Reproduce**
1. Open https://github.com/chouglesaud/repositree, it works fine.
2. Open https://github.com/chouglesaud/repositree/, it doesn't work!

- Repositree Version: 1.5.1

**Comment by chouglesaud** [comment]
Bugfixed :+1: 

Update the extension
Repositree v.1.6.0
